name: Example

on:
  pull_request:
  push:
    branches: main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: validate
        uses: ./
        with:
          path: examples/multi-invalid-valid.yaml
          fail: false
      - run: |
          jq <<'EOM'
          ${{ steps.validate.outputs.invalid-services }}
          EOM
